/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.require("sap.m.FlexBoxCssPropertyMap");jQuery.sap.declare("sap.m.FlexBoxStylingHelper");sap.m.FlexBoxStylingHelper={};
sap.m.FlexBoxStylingHelper.setFlexBoxStyles=function(r,c){var d;var i=c.getDisplayInline();var D=c.getDirection().replace(/\W+/g,"-").replace(/([a-z\d])([A-Z])/g,"$1-$2").toLowerCase();var f=c.getFitContainer();var j=c.getJustifyContent().replace(/\W+/g,"-").replace(/([a-z\d])([A-Z])/g,"$1-$2").toLowerCase();var a=c.getAlignItems().replace(/\W+/g,"-").replace(/([a-z\d])([A-Z])/g,"$1-$2").toLowerCase();if(i){d="inline-flex"}else{d="flex"}if(f&&!(c.getParent()instanceof sap.m.FlexBox)){r.addStyle("width","auto");r.addStyle("height","100%")}if(j==="start"||j==="end"){j="flex-"+j}if(a==="start"||a==="end"){a="flex-"+a}sap.m.FlexBoxStylingHelper.setStyle(r,c,"display",d);if(D!=="row"){sap.m.FlexBoxStylingHelper.setStyle(r,c,"flex-direction",D)}if(j!=="flex-start"){sap.m.FlexBoxStylingHelper.setStyle(r,c,"justify-content",j)}if(a!=="stretch"){sap.m.FlexBoxStylingHelper.setStyle(r,c,"align-items",a)}};
sap.m.FlexBoxStylingHelper.setFlexItemStyles=function(r,l){var o="";var g="";var a="";o=l.getOrder();if(o){sap.m.FlexBoxStylingHelper.setStyle(r,null,"order",o)}g=l.getGrowFactor();if(g){sap.m.FlexBoxStylingHelper.setStyle(r,null,"flex-grow",g)}a=l.getAlignSelf().toLowerCase();if(a==="start"||a==="end"){a="flex-"+a}if(a&&a!=="flex-start"){sap.m.FlexBoxStylingHelper.setStyle(r,null,"align-self",a)}};
sap.m.FlexBoxStylingHelper.setStyle=function(r,c,p,v){if(typeof(v)==="string"){v=v.toLowerCase()}var V=[];if(jQuery.browser.webkit){V=["-webkit-"]}else if(jQuery.browser.mozilla){V=["-moz-"]}var s=["spec0907"];for(var i=0;i<s.length;++i){var S=s[i];if(sap.m.FlexBoxCssPropertyMap[S][p]===null||sap.m.FlexBoxCssPropertyMap[S][p]==="<idem>"){continue}var l=null;if(typeof(sap.m.FlexBoxCssPropertyMap[S][p])==="object"){if(sap.m.FlexBoxCssPropertyMap[S][p]["<number>"]){l=sap.m.FlexBoxCssPropertyMap[S][p]["<number>"];for(var k in l){l[k]=v}}else{l=sap.m.FlexBoxCssPropertyMap[S][p][v]}}else{l=sap.m.FlexBoxCssPropertyMap[S][p][v]}if(l===null||l==="<idem>"){continue}else if(typeof(l)==="object"){for(var L in l){if(L==="display"){for(var k in V){if(V[k]+l[L]==="-webkit-flexbox"||V[k]+l[L]==="-webkit-inline-flexbox")continue;if(r){r.addStyle(L,V[k]+l[L])}else{jQuery(c).css(L,V[k]+l[L])}}}else{for(var k in V){if(r){r.addStyle(V[k]+L,l[L])}else{jQuery(c).css(V[k]+L,l[L])}}}}}}};
