/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.List");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.List",{metadata:{publicMethods:["getSelectedItem","setSelectedItem","getSelectedItems","setSelectedItemById","removeSelections"],library:"sap.m",properties:{"inset":{type:"boolean",group:"Misc",defaultValue:false},"visible":{type:"boolean",group:"Appearance",defaultValue:true},"headerText":{type:"string",group:"Misc",defaultValue:null},"footerText":{type:"string",group:"Misc",defaultValue:null},"mode":{type:"sap.m.ListMode",group:"Appearance",defaultValue:sap.m.ListMode.None},"width":{type:"sap.ui.core.CSSSize",group:"Dimension",defaultValue:'100%'},"includeItemInSelection":{type:"boolean",group:"Misc",defaultValue:false}},defaultAggregation:"items",aggregations:{"items":{type:"sap.m.ListItemBase",multiple:true,singularName:"item",bindable:"bindable"}},events:{"select":{},"delete":{}}}});sap.m.List.M_EVENTS={'select':'select','delete':'delete'};
sap.m.List.prototype.init=function(){this._mode=this.getMode();this._includeItemInSelection=this.getIncludeItemInSelection()};
sap.m.List.prototype.getSelectedItem=function(){var r;switch(this.getMode()){case sap.m.ListMode.SingleSelect:var I=this.getItems();for(var i=0;i<I.length;i++){if(I[i]._radioButton.getSelected()){r=I[i];break}}break;case sap.m.ListMode.MultiSelect:var I=this.getItems();for(var i=0;i<I.length;i++){if(I[i]._checkBox.getSelected()){r=I[i];break}}break;case sap.m.ListMode.None:r=null;break}return r};
sap.m.List.prototype.setSelectedItem=function(l,s){var L=sap.ui.getCore().byId(l._listId);switch(this.getMode()){case sap.m.ListMode.SingleSelect:l._radioButton.setSelected(s);l.$().toggleClass('sapMLIBSelected',s);if(L._previousSingleSelect&&L._previousSingleSelect!==l){L._previousSingleSelect.$().toggleClass('sapMLIBSelected',false)}L._previousSingleSelect=l;break;case sap.m.ListMode.MultiSelect:l._checkBox.setSelected(s);l.$().toggleClass('sapMLIBSelected',s);break;case sap.m.ListMode.None:}return this};
sap.m.List.prototype.getSelectedItems=function(){var r=[];switch(this.getMode()){case sap.m.ListMode.SingleSelect:var I=this.getItems();for(var i=0;i<I.length;i++){if(I[i]._radioButton.getSelected()){r.push(I[i])}}break;case sap.m.ListMode.MultiSelect:var I=this.getItems();for(var i=0;i<I.length;i++){if(I[i]._checkBox.getSelected()){r.push(I[i])}}break;case sap.m.ListMode.None:break}return r};
sap.m.List.prototype.setSelectedItemById=function(i,s){var l=sap.ui.getCore().byId(L._listId);switch(this.getMode()){case sap.m.ListMode.SingleSelect:var L=sap.ui.getCore().byId(i);if(L){L._radioButton.setSelected(s);L.$().toggleClass('sapMLIBSelected',s);if(l._previousSingleSelect&&l._previousSingleSelect!==L){l._previousSingleSelect.$().toggleClass('sapMLIBSelected',false)}l._previousSingleSelect=L}break;case sap.m.ListMode.MultiSelect:var L=sap.ui.getCore().byId(i);if(L){L._checkBox.setSelected(s);L.$().toggleClass('sapMLIBSelected',s)}break;case sap.m.ListMode.None:break}return this};
sap.m.List.prototype.removeSelections=function(){this._removeCurrentSelection()};
sap.m.List.prototype._select=function(e){var l=sap.ui.getCore().byId(this.oParent.getId());var L=sap.ui.getCore().byId(l._listId);l.$().toggleClass('sapMLIBSelected');if(L.getMode()===sap.m.ListMode.SingleSelect){if(L._previousSingleSelect&&L._previousSingleSelect!==l){L._previousSingleSelect.$().toggleClass('sapMLIBSelected',false)}L._previousSingleSelect=l}if(!L.getIncludeItemInSelection()){L.fireSelect({listItem:l})}};
sap.m.List.prototype._selectTapped=function(l){this.fireSelect({listItem:l})};
sap.m.List.prototype._delete=function(e){var l=sap.ui.getCore().byId(this.oParent.getId());var L=sap.ui.getCore().byId(l._listId);L.fireDelete({listItem:l})};
sap.m.List.prototype._removeCurrentSelection=function(){switch(this._mode){case sap.m.ListMode.SingleSelect:var I=this.getItems();for(var i=0;i<I.length;i++){I[i]._radioButton.setSelected(false);I[i].$().toggleClass('sapMLIBSelected',false)}break;case sap.m.ListMode.MultiSelect:var I=this.getItems();for(var i=0;i<I.length;i++){I[i]._checkBox.setSelected(false);I[i].$().toggleClass('sapMLIBSelected',false)}break;case sap.m.ListMode.None:break}};
