/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.Page");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.Page",{metadata:{publicMethods:["scrollTo"],library:"sap.m",properties:{"title":{type:"string",group:"Data",defaultValue:null},"showNavButton":{type:"boolean",group:"Appearance",defaultValue:false},"showHeader":{type:"boolean",group:"Appearance",defaultValue:true},"navButtonText":{type:"string",group:"Misc",defaultValue:null},"enableScrolling":{type:"boolean",group:"Behavior",defaultValue:true},"icon":{type:"sap.ui.core.URI",group:"Appearance",defaultValue:null},"backgroundDesign":{type:"sap.m.PageBackgroundDesign",group:"Appearance",defaultValue:sap.m.PageBackgroundDesign.Standard}},defaultAggregation:"content",aggregations:{"content":{type:"sap.ui.core.Control",multiple:true,singularName:"content"},"customHeader":{type:"sap.m.Bar",multiple:false},"footer":{type:"sap.m.Bar",multiple:false},"subHeader":{type:"sap.m.Bar",multiple:false}},events:{"navButtonTap":{}}}});sap.m.Page.M_EVENTS={'navButtonTap':'navButtonTap'};
sap.m.Page.prototype.init=function(){this._rb=sap.ui.getCore().getLibraryResourceBundle("sap.m");if(this.getNavButtonText()==""){this.setNavButtonText(this._rb.getText("PAGE_NAVBUTTON_TEXT"))}};
sap.m.Page.prototype._hasScrolling=function(){return!(jQuery.browser.msie&&jQuery.browser.version<9)&&this.getEnableScrolling()};
sap.m.Page.prototype.onBeforeRendering=function(){if(this._oScroller&&!this._hasScrolling()){this._oScroller.destroy();this._oScroller=null}else if(this._hasScrolling()&&!this._oScroller){jQuery.sap.require("sap.ui.core.delegate.ScrollEnablement");this._oScroller=new sap.ui.core.delegate.ScrollEnablement(this,this.getId()+"-scroll",{horizontal:false,vertical:true,zynga:false,preventDefault:false,nonTouchScrolling:true})}};
sap.m.Page.prototype.exit=function(){if(this._oScroller){this._oScroller.destroy();this._oScroller=null}if(this._headerTitle){this._headerTitle.destroy();this._headerTitle=null}if(this._navBtn){this._navBtn.destroy();this._navBtn=null}if(this._appIcon){this._appIcon.destroy();this._appIcon=null}if(this._internalHeader){this._internalHeader.destroy();this._internalHeader=null}};
sap.m.Page.prototype.setBackgroundDesign=function(b){var s=this._hasScrolling();var B=this.getBackgroundDesign();this.setProperty("backgroundDesign",b,true);if(s){jQuery.sap.byId(this.getId()+"-scroll").removeClass('sapMPageBg'+B).addClass('sapMPageBg'+this.getBackgroundDesign())}else{jQuery.sap.byId(this.getId()+"-cont").removeClass('sapMPageBg'+B).addClass('sapMPageBg'+this.getBackgroundDesign())}return this};
sap.m.Page.prototype.setTitle=function(t){this._headerTitle=this._headerTitle||new sap.m.Label(this.getId()+"-title",{text:t});this._headerTitle.setText(t);if(jQuery.os.ios){this._updateHeaderContent(this._headerTitle,'middle',0)}else{this._titleIndex=this._titleIndex||0;this._updateHeaderContent(this._headerTitle,'left',this._titleIndex)}this.setProperty("title",t,true);return this};
sap.m.Page.prototype.setShowNavButton=function(s){this.setProperty("showNavButton",s,true);this._navBtn=this._navBtn||new sap.m.Button(this.getId()+"-navButton",{tap:jQuery.proxy(this.fireNavButtonTap,this)});if(jQuery.os.ios){this._navBtn.setType(sap.m.ButtonType.Back);this._navBtn.setText(this.getNavButtonText())}else{this._navBtn.setType(sap.m.ButtonType.Up)}if(s){if(!jQuery.os.ios&&this.getIcon()){this._navBtn.setIcon(this.getIcon())}if(this._appIcon){this._updateHeaderContent(this._appIcon,'left',-1)}this._updateHeaderContent(this._navBtn,'left',0)}else{this._updateHeaderContent(this._navBtn,'left',-1);if(!jQuery.os.ios&&this.getIcon()){this._appIcon=this._appIcon||new sap.m.Image(this.getId()+"-icon",{src:this.getIcon()});this._updateHeaderContent(this._appIcon,'left',0)}}return this};
sap.m.Page.prototype.setNavButtonText=function(t){this._navBtn=this._navBtn||new sap.m.Button(this.getId()+"-navButton",{tap:jQuery.proxy(this.fireNavButtonTap,this)});if(t==""){t=this._rb.getText("PAGE_NAVBUTTON_TEXT")}if(jQuery.os.ios){this._navBtn.setText(t)}this.setProperty("navButtonText",t,true);return this};
sap.m.Page.prototype.setIcon=function(i){if(!jQuery.os.ios){if(this.getShowNavButton()){this._navBtn=this._navBtn||new sap.m.Button(this.getId()+"-navButton",{tap:jQuery.proxy(this.fireNavButtonTap,this)});this._navBtn.setIcon(i);if(this._appIcon){this._updateHeaderContent(this._appIcon,'left',-1)}}else{this._appIcon=this._appIcon||new sap.m.Image(this.getId()+"-icon",{src:i});this._appIcon.setSrc(i);if(this._navBtn){this._updateHeaderContent(this._navBtn,'left',-1)}this._updateHeaderContent(this._appIcon,'left',0)}this._titleIndex=1}this.setProperty("icon",i,true);return this};
sap.m.Page.prototype._updateHeaderContent=function(c,C,i){if(this._internalHeader){switch(C){case'left':if(i==-1){this._internalHeader.removeContentLeft(c)}else{if(this._internalHeader.indexOfContentLeft(c)!=i){this._internalHeader.insertContentLeft(c,i);this._internalHeader.invalidate()}}break;case'middle':if(i==-1){this._internalHeader.removeContentMiddle(c)}else{if(this._internalHeader.indexOfContentMiddle(c)!=i){this._internalHeader.insertContentMiddle(c,i);this._internalHeader.invalidate()}}break;case'right':if(i==-1){this._internalHeader.removeContentRight(c)}else{if(this._internalHeader.indexOfContentRight(c)!=i){this._internalHeader.insertContentRight(c,i);this._internalHeader.invalidate()}}break;default:break}}};
sap.m.Page.prototype._getInternalHeader=function(){if(!this._internalHeader){this._internalHeader=new sap.m.Bar(this.getId()+"-intHeader");this._internalHeader.setParent(this,'internalHeader',true)}if(jQuery.os.ios){if(this.getShowNavButton()&&this._navBtn){this._updateHeaderContent(this._navBtn,'left',0)}if(this.getTitle()&&this._headerTitle){this._updateHeaderContent(this._headerTitle,'middle',0)}}else{if(this.getShowNavButton()&&this._navBtn){this._updateHeaderContent(this._navBtn,'left',0);this._titleIndex=1}else{if(this.getIcon()&&this._appIcon){this._updateHeaderContent(this._appIcon,'left',0);this._titleIndex=1}}if(this.getTitle()&&this._headerTitle){this._titleIndex=this._titleIndex||0;this._updateHeaderContent(this._headerTitle,'left',this._titleIndex)}}this._internalHeader._context='header';return this._internalHeader};
sap.m.Page.prototype._getAnyHeader=function(){var c=this.getCustomHeader();if(c){c._context='header';return c.addStyleClass('sapMPageHeader').addStyleClass("sapMHeader-CTX")}else{return this._getInternalHeader().addStyleClass('sapMPageHeader').addStyleClass("sapMHeader-CTX")}};
sap.m.Page.prototype.scrollTo=function(y,t){if(this._oScroller&&this.getDomRef()){this._oScroller.scrollTo(0,y,t)}else{this._oScroller._scrollX=0;this._oScroller._scrollY=y}return this};
