/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.Slider");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.Slider",{metadata:{publicMethods:["stepUp","stepDown"],library:"sap.m",properties:{"width":{type:"sap.ui.core.CSSSize",group:"Appearance",defaultValue:"100%"},"enabled":{type:"boolean",group:"Behavior",defaultValue:true},"visible":{type:"boolean",group:"Appearance",defaultValue:true},"name":{type:"string",group:"Misc",defaultValue:""},"min":{type:"int",group:"Data",defaultValue:0},"max":{type:"int",group:"Data",defaultValue:100},"step":{type:"int",group:"Data",defaultValue:1},"progress":{type:"boolean",group:"Misc",defaultValue:true},"value":{type:"int",group:"Data",defaultValue:0}},events:{"change":{},"liveChange":{}}}});sap.m.Slider.M_EVENTS={'change':'change','liveChange':'liveChange'};jQuery.sap.require("sap.ui.core.EnabledPropagator");sap.m.Slider.prototype._aVEvents=["_ontouchstart","_ontouchmove","_ontouchend"];sap.m.Slider.prototype._aEvents=["ontouchstart","ontouchmove","ontouchend"];
sap.m.Slider.prototype.onBeforeRendering=function(){var m=this.getMax(),M=this.getMin(),s=this.getStep(),b=false,e=false;if(M>=m){b=true;e=true;jQuery.sap.log.warning("Property wrong min: "+M+" >= max: "+m+" on "+this)}if(s<1){jQuery.sap.log.warning("The step could not be negative on "+this);s=1;this.setProperty("step",s,true)}if((s>(m-M))&&!b){e=true;jQuery.sap.log.warning("Property wrong step: "+s+" > max: "+m+" - "+"min: "+M+" on "+this)}if(!e){this.setValue(this.getValue());this.iProgressValue=this._getPercentageFromValue(this.getValue())}};
sap.m.Slider.prototype.onAfterRendering=function(){(this.getEnabled())?this._bindEvents():this._unbindEvents();this._$SldContainer=this.$();this._$Sld=this._$SldContainer.children(".sapMSld");this._$Thumb=this._$Sld.children(".sapMSldThumb");this._$Input=this._$SldContainer.children("input[type=range]")};
sap.m.Slider.prototype._ontouchstart=function(e){var t=jQuery(e.target),m=this.getMin(),v;e.originalEvent._sapui_handledByControl=true;if(e.targetTouches.length>1){return}this._calcMeasures();this._iDiffX=this._fSldPaddingRight;this._iStartValue=this.getValue();this._$Sld.addClass("sapMSldPressed");if(t.is(this._$Thumb)||t.parent().is(this._$Thumb)){this._iDiffX=e.targetTouches[0].pageX-this._$Thumb.offset().left}else{v=Math.round((((e.targetTouches[0].pageX-this._fSldPaddingRight-this._iSldOffsetLeft)/this._iSldWidth)*(this.getMax()-m))+m);this.setValue(v)}};
sap.m.Slider.prototype._ontouchmove=function(e){var m=this.getMin(),v=this.getValue(),n=Math.round((((e.targetTouches[0].pageX-this._iDiffX-this._iSldOffsetLeft)/this._iSldWidth)*(this.getMax()-m))+m);this.setValue(n);n=this.getValue();if(v!==n){this.fireLiveChange({value:n})}};
sap.m.Slider.prototype._ontouchend=function(){this._$Sld.removeClass("sapMSldPressed");if(this._iStartValue!==this.getValue()){this.fireChange({value:this.getValue()})}delete this._iDiffX;delete this._iStartValue};
sap.m.Slider.prototype._sBackgroundSizeRemainder=(function(){switch(jQuery.os.os){case"ios":return"% 0.4375em, 100%";break;case"android":case"blackberry":return"% 0.1875em";break}})();
sap.m.Slider.prototype._calcMeasures=function(){this._iSldWidth=this._$SldContainer.width();this._fSldPaddingRight=parseFloat(this._$SldContainer.css("padding-right"),10);this._iSldOffsetLeft=this._$SldContainer.offset().left;this._iThumbWidth=this._$Thumb.width()};
sap.m.Slider.prototype._bindEvents=function(){var i;for(i=0;i<this._aVEvents.length;i++){this[this._aEvents[i]]=this[this._aVEvents[i]]}return this};
sap.m.Slider.prototype._unbindEvents=function(){var i;for(i=0;i<this._aVEvents.length;i++){this[this._aEvents[i]]=null}return this};
sap.m.Slider.prototype._getPercentageFromValue=function(v){var m=this.getMin();return((v-m)/(this.getMax()-m))*100};
sap.m.Slider.prototype._validateStep=function(n){return(typeof n==="undefined")?1:this.validateProperty("value",n)};
sap.m.Slider.prototype.stepUp=function(n){return this.setValue(this.getValue()+(this._validateStep(n)*this.getStep()))};
sap.m.Slider.prototype.stepDown=function(n){return this.setValue(this.getValue()-(this._validateStep(n)*this.getStep()))};
sap.m.Slider.prototype.setValue=function(v){var m=this.getMax(),M=this.getMin(),s=this.getStep(),c=this.getValue(),r=Math.abs(v%s),p;v=this.validateProperty("value",v);v=(r>=s/2)?v+s-r:v-r;v=(v>m)?m:(v<M)?M:v;this.setProperty("value",v,true);if(c===this.getValue()){return this}if(this._$Sld instanceof jQuery){this._$Input.attr("value",v);p=this._getPercentageFromValue(v);if(this.getProgress()){this._$Sld.css("-webkit-background-size",p+this._sBackgroundSizeRemainder)}this._$Thumb.css("left",p+"%")}return this};
