/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.m.Switch");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.m.Switch",{metadata:{library:"sap.m",properties:{"visible":{type:"boolean",group:"Appearance",defaultValue:true},"state":{type:"boolean",group:"Misc",defaultValue:false},"enabled":{type:"boolean",group:"Data",defaultValue:true},"name":{type:"string",group:"Misc",defaultValue:""}},events:{"change":{}}}});sap.m.Switch.M_EVENTS={'change':'change'};sap.m.Switch.prototype._aVEvents=["_ontouchstart","_ontouchmove","_ontouchend","_ontouchcancel"];sap.m.Switch.prototype._aEvents=["ontouchstart","ontouchmove","ontouchend","ontouchcancel"];sap.m.Switch.prototype._iTransitionTime=175;sap.m.Switch.prototype._bAndroidStyle=!!(jQuery.os.android||jQuery.os.blackberry);sap.m.Switch.prototype._bTransition=!!(jQuery.os.ios);
sap.m.Switch.prototype.init=function(){var r=sap.ui.getCore().getLibraryResourceBundle("sap.m");this._sOn=r.getText("SWITCH_ON");this._sOff=r.getText("SWITCH_OFF");if(this._bAndroidStyle){this._aVEvents.push("_onswiperight","_onswipeleft");this._aEvents.push("onswiperight","onswipeleft")}};
sap.m.Switch.prototype.onAfterRendering=function(){if(this.getEnabled()){this._bindEvents()}this._$Swt=this.$();this._iOffsetX=(jQuery.os.ios)?1:(this._bAndroidStyle)?7:0;this._iSwtWidth=this._$Swt.width();this._iSwtMp=Math.round(this._iSwtWidth/2);this._$Btn=this._$Swt.children(".sapMSwtBtn");this._iBtnOuterWidth=this._$Btn.outerWidth(true);this._iBtnWidth=this._$Btn.width();this._iBtnMp=Math.round(this._iBtnOuterWidth/2);this._iBtnMaxLeft=(this._iSwtWidth-this._iBtnOuterWidth)+this._iOffsetX;this._iBtnMinLeft=-this._iOffsetX;this._$Checkbox=this._$Swt.children("input[type=checkbox]");if(jQuery.os.ios){this._$TextOn=this._$Swt.children('.sapMSwtTextOn');this._iTextOnIndentMax=13;this._iTextOnIndentMin=-37;this._$TextOff=this._$Swt.children('.sapMSwtTextOff')}};
sap.m.Switch.prototype._onswiperight=function(e){this.setState(true,true)};
sap.m.Switch.prototype._onswipeleft=function(e){this.setState(false,true)};
sap.m.Switch.prototype._ontouchstart=function(e){var t=e.targetTouches[0];e.originalEvent._sapui_handledByControl=true;if(sap.m.touch.countContained(e.touches,this.getId())>1){return}this._iActiveTouch=t.identifier;this._$Swt.addClass("sapMSwtPressed");this._bTempState=this.getState();this._iStarTouchPageX=t.pageX;this._iCurrentTouchPageX=this._iStarTouchPageX;this._iDiffX=this._iStarTouchPageX-this._$Btn.position().left;this._bTargetBtn=jQuery(e.target).is(this._$Btn);this._bDrag=false;if(this._bTransition){this._$Swt.removeClass("sapMSwtTrans")}};
sap.m.Switch.prototype._ontouchmove=function(e){var t,T,i,d,l,b,f=sap.m.touch;t=f.find(e.changedTouches,this._iActiveTouch);if(!t||(this._bAndroidStyle&&!this._bTargetBtn)){return}i=t.pageX;d=i-this._iCurrentTouchPageX;l=(this._bTargetBtn&&this._bAndroidStyle)?i-this._iDiffX:d+this._$Btn.position().left;b=l+this._iBtnMp;l=(l>this._iBtnMaxLeft)?this._iBtnMaxLeft:(l<this._iBtnMinLeft)?this._iBtnMinLeft:l;this._bDrag=true;this._iCurrentTouchPageX=i;if(this._iCurrentLeft===l){return}this._iCurrentLeft=l;this._$Btn.css("left",l+"px");if(b>=this._iSwtMp){if(!this._bTempState){if(this._bAndroidStyle){this._$Btn.attr("data-sap-ui-swt",this._sOn)}this._bTempState=true}}else if(this._bTempState){if(this._bAndroidStyle){this._$Btn.attr("data-sap-ui-swt",this._sOff)}this._bTempState=false}if(jQuery.os.ios){T=parseInt(this._$TextOn.css("text-indent"),10)+d;T=(T>this._iTextOnIndentMax)?this._iTextOnIndentMax:(T<this._iTextOnIndentMin)?this._iTextOnIndentMin:T;this._$TextOn.css({width:l+this._iBtnWidth+this._iOffsetX,textIndent:T});this._$TextOff.width(this._iSwtWidth-(l+this._iOffsetX))}};
sap.m.Switch.prototype._ontouchend=function(e){var p=["_bTempState","_iStarTouchPageX","_iCurrentTouchPageX","_iDiffX","_bTargetBtn","_bDrag","_iActiveTouch"],l=p.length,t=sap.m.touch,i;if(!t.find(e.changedTouches,this._iActiveTouch)){return}this._$Swt.removeClass("sapMSwtPressed");(this._bDrag)?this.setState(this._bTempState,true):this.setState(!this._bTempState,true);for(i=0;i<l;i++){if(this.hasOwnProperty(p[i])){delete this[p[i]]}}};
sap.m.Switch.prototype._ontouchcancel=function(e){this._ontouchend(e)};
sap.m.Switch.prototype._bindEvents=function(){var i;for(i=0;i<this._aVEvents.length;i++){this[this._aEvents[i]]=this[this._aVEvents[i]]}return this};
sap.m.Switch.prototype._unbindEvents=function(){var i;for(i=0;i<this._aVEvents.length;i++){this[this._aEvents[i]]=null}return this};
sap.m.Switch.prototype.setState=function(s,t){var s,S,n,a,i;if(!this.getEnabled()&&t){return this}n=!(this.getState()===s);if(n){this.setProperty("state",s,true)}if(!(this._$Swt instanceof jQuery)){return this}s=this.getState();S=s?this._sOn:this._sOff;if(n){if(this._bAndroidStyle){this._$Btn.attr("data-sap-ui-swt",S)}this._$Checkbox.attr({checked:s,value:S});(s)?this._$Swt.removeClass("sapMSwtOff").addClass("sapMSwtOn"):this._$Swt.removeClass("sapMSwtOn").addClass("sapMSwtOff");if(t){if(this._bTransition){jQuery.sap.delayedCall(this._iTransitionTime,this,function _fireChangeDelay(s){this.fireChange({state:s})},[s])}else{this.fireChange({state:s})}}}if(this._bTransition){this._$Swt.addClass("sapMSwtTrans")}a=[this._$Btn];if(jQuery.os.ios){a.push(this._$TextOn,this._$TextOff)}for(i=0;i<a.length;i++){a[i].removeAttr("style")}return this};
sap.m.Switch.prototype.setEnabled=function(v){if(this.getEnabled()===v){return this}this.setProperty("enabled",v,true);if(this._$Swt instanceof jQuery){(v)?this._bindEvents()._$Swt.removeClass("sapMSwtDisabled"):this._unbindEvents()._$Swt.addClass("sapMSwtDisabled");this._$Checkbox.attr("disabled",!v)}return this};
