/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.model.odata.ODataListBinding");jQuery.sap.require("sap.ui.model.odata.Filter");jQuery.sap.require("sap.ui.model.ListBinding");jQuery.sap.require("sap.ui.core.format.DateFormat");
sap.ui.model.odata.ODataListBinding=function(m,p,c,s,f,P){sap.ui.model.ListBinding.apply(this,arguments);this.sFilterParams=null;this.sSortParams=null;this.sRangeParams=null;this.sCustomParams=this.oModel.createCustomParams(this.mParameters);this.aPredefinedFilters=f;this.iStartIndex=0;this.bPendingChange=false;this.aKeys=[];this.bInitialized=false;var C=this.sPath;C=p.substr(p.lastIndexOf("/")+1);this.oEntityType=this.oModel._getEntityType(C);this.oDateTimeFormat=sap.ui.core.format.DateFormat.getDateInstance({pattern:"'datetime'''yyyy-MM-dd'T'HH:mm:ss''"});this.oDateTimeOffsetFormat=sap.ui.core.format.DateFormat.getDateInstance({pattern:"'datetimeoffset'''yyyy-MM-dd'T'HH:mm:ss'Z'''"});this.createSortParams(this.oSorter);this.createFilterParams(this.aFilters);var r=this.oModel._getObject(p,c);if(jQuery.isArray(r)){this.aKeys=r;this.iLength=r.length;this.bLengthFinal=true}else{this.iLength=0;this.bLengthFinal=false;if(this.oModel.isCountSupported()){this._getLength()}}};
sap.ui.model.odata.ODataListBinding.prototype=jQuery.sap.newObject(sap.ui.model.ListBinding.prototype);sap.ui.base.Object.defineClass("sap.ui.model.odata.ODataListBinding",{baseType:"sap.ui.model.ListBinding",publicMethods:["getLength"]});
sap.ui.model.odata.ODataListBinding.prototype.getContexts=function(s,l,t){this.bInitialized=true;if(!s){s=0}if(!l){l=this.oModel.iSizeLimit}if(this.bLengthFinal){if(s+l>this.iLength){l=this.iLength-s}if(l<0){l=0}}var c=[],k,C;for(var i=s;i<s+l;i++){k=this.aKeys[i];if(!k){break}C=this.oModel.getContext(k);c.push(C)}if(t&&(t<=l||c.length===l)){t=undefined}var S=s;var a=l;if(t){var b=Math.floor(s/(t/2));var S=Math.floor(b*(t/2));var a=this.bLengthFinal?Math.min(this.iLength-S,t):Math.max(l,t);if(!this.bPendingRequest&&a>0){this.loadData(S,a)}}else{if(!this.bPendingRequest&&l>0&&c.length!=l){this.loadData(s,l)}}return c};
sap.ui.model.odata.ODataListBinding.prototype.setContext=function(c){if(this.oContext!=c){this.oContext=c;if(this.bInitialized){var r=this.oModel._getObject(this.sPath,this.oContext);if(jQuery.isArray(r)){this.aKeys=r;this.iLength=r.length;this.bLengthFinal=true;this._fireChange()}else{this.aKeys=[];this.loadData()}}}};
sap.ui.model.odata.ODataListBinding.prototype.loadData=function(s,l,S){var t=this;this.bPendingRequest=true;var c=undefined;if(arguments.length===1&&typeof s==="function"){c=s;s=undefined}if(s||l){this.sRangeParams="$skip="+s+"&$top="+l;this.iStartIndex=s}else{s=this.iStartIndex}var p=[];if(this.sRangeParams){p.push(this.sRangeParams)}if(this.sSortParams){p.push(this.sSortParams)}if(this.sFilterParams){p.push(this.sFilterParams)}if(this.sCustomParams){p.push(this.sCustomParams)}p.push("$inlinecount=allpages");function _(d){jQuery.each(d.results,function(i,e){t.aKeys[s+i]=t.oModel._getKey(e)});if(d.__count){t.iLength=parseInt(d.__count,10);t.bLengthFinal=true}if(t.iLength<s+d.results.length){t.iLength=s+d.results.length;t.bLengthFinal=false}if(d.results.length<l){t.iLength=s+d.results.length;t.bLengthFinal=true}if(d.results.length==0){t.iLength=0;t.bLengthFinal=true}t.bPendingRequest=false;if(c){c.call(t)}}var P=this.sPath,C=this.oContext,I=!jQuery.sap.startsWith(P,"/");if(I){if(C){P=C+"/"+P}else{P=this.oModel.isLegacySyntax()?"/"+P:undefined}}if(P){this.oModel._loadData(P,p,_,function(){if(c){c.call(t)}},this.getContext())}};
sap.ui.model.odata.ODataListBinding.prototype.getLength=function(){return this.iLength};
sap.ui.model.odata.ODataListBinding.prototype._getLength=function(){var t=this;var p=[];if(this.sFilterParams){p.push(this.sFilterParams)}function _(d){t.iLength=parseInt(d,10);t.bLengthFinal=true}function a(x,e,E){jQuery.sap.log.warning("Request for $count failed: "+e,x.responseText+","+x.status+","+x.statusText)}var P=this.sPath,c=this.oContext,i=!jQuery.sap.startsWith(P,"/");if(i){if(c){P=c+"/"+P}else{P=this.oModel.isLegacySyntax()?"/"+P:undefined}}if(P){var r=this.oModel._createRequest(P+"/$count",p,false);jQuery.ajax({url:r.requestUri,async:r.async,cache:this.oModel.bCache,username:r.user,password:r.password,success:_,error:a})}};
sap.ui.model.odata.ODataListBinding.prototype.checkUpdate=function(f){this._fireChange()};
sap.ui.model.odata.ODataListBinding.prototype.sort=function(s){this.createSortParams(s);this.aKeys=[];this.loadData(function(){this._fireSort({sorter:s})})};
sap.ui.model.odata.ODataListBinding.prototype.createSortParams=function(s){if(s){this.sSortParams="$orderby="+s.sPath;this.sSortParams+=s.bDescending?"%20desc":"%20asc"}else{this.sSortParams=null}};
sap.ui.model.odata.ODataListBinding.prototype.filter=function(f){if(!f){f=[]}if(this.aPredefinedFilters){f=f.concat(this.aPredefinedFilters)}this.createFilterParams(f);this.aKeys=[];this.iLength=0;this.bLengthFinal=false;this.loadData(function(){this._fireFilter({filters:f})})};
sap.ui.model.odata.ODataListBinding.prototype.createFilterParams=function(f){if(f&&f.length>0){var F={},a=0,b,s="$filter=(",c=0,t=this;jQuery.each(f,function(j,o){b=F[o.sPath];if(!b){b=F[o.sPath]=[];a++}b.push(o)});jQuery.each(F,function(p,b){s+='(';jQuery.each(b,function(i,o){if(o instanceof sap.ui.model.odata.Filter){if(b.length>1){s+='('}jQuery.each(o.aValues,function(i,d){if(i>0){if(o.bAND){s+=")%20and%20("}else{s+=")%20or%20("}}s=t._createFilterSegment(o.sPath,d.operator,d.value1,d.value2,s)});if(b.length>1){s+=')'}}else{s=t._createFilterSegment(o.sPath,o.sOperator,o.oValue1,o.oValue2,s)}if(i<b.length-1){s+=")%20or%20("}});s+=')';if(c<a-1){s+=")%20and%20("}c++});s+=")";this.sFilterParams=s}else{this.sFilterParams=null}};
sap.ui.model.odata.ODataListBinding.prototype._createFilterSegment=function(p,o,v,V,f){var P;if(this.oEntityType){P=this.oModel._getPropertyMetadata(this.oEntityType,p)}if(P){switch(P.type){case"Edm.String":v="'"+String(v).replace(/'/g,"''")+"'";V=(V)?"'"+String(V).replace(/'/g,"''")+"'":null;break;case"Edm.Time":v="time'"+v+"'";V=(V)?"time'"+V+"'":null;break;case"Edm.DateTime":v=this.oDateTimeFormat.format(new Date(v));V=(V)?this.oDateTimeFormat.format(new Date(V)):null;break;case"Edm.DateTimeOffset":v=this.oDateTimeOffsetFormat.format(new Date(v));V=(V)?this.oDateTimeOffsetFormat.format(new Date(V)):null;break;case"Edm.Guid":v="guid'"+v+"'";V=(V)?"guid'"+V+"'":null;break;case"Edm.Binary":v="binary'"+v+"'";V=(V)?"binary'"+V+"'":null;break;default:break}}else{if(isNaN(v)){if(!isNaN(Date.parse(v))){v=this.oDateTimeFormat.format(new Date(v))}else{v="'"+v+"'"}}if(V){if(isNaN(V)){if(!isNaN(Date.parse(V))){V=this.oDateTimeFormat.format(new Date(V))}else{V="'"+V+"'"}}}}switch(o){case"EQ":case"NE":case"GT":case"GE":case"LT":case"LE":f+=p+"%20"+o.toLowerCase()+"%20"+v;break;case"BT":f+=p+"%20gt%20"+v+"%20and%20"+p+"%20lt%20"+V;break;case"Contains":f+="indexof("+p+","+v+")%20ne%20-1";break;case"StartsWith":f+="startswith("+p+","+v+")%20eq%20true";break;case"EndsWith":f+="endswith("+p+","+v+")%20eq%20true";break;default:f+="true"}return f};
sap.ui.model.odata.ODataListBinding.prototype._refresh=function(){this.aKeys=[];this.bLengthFinal=false;this.checkUpdate()};
